/**
 * Content translation module for RAG responses
 * PWS 3.1.9: Multilingual Functionality with an English Dataset
 *
 * Translates English knowledge base content into supported languages.
 * In production, this would use an LLM API (Claude/OpenAI) for real-time translation.
 * This module provides pre-translated versions of all seeded knowledge base documents.
 */

import type { SupportedLanguage } from './i18n';

// Pre-translated knowledge base content keyed by document ID
const TRANSLATED_CONTENT: Record<string, Record<SupportedLanguage, string>> = {
  'doc-001': {
    en: '', // Use original
    es: `El Cuerpo de Paz es un programa de voluntariado del gobierno de los Estados Unidos. Fue establecido por el presidente John F. Kennedy el 1 de marzo de 1961 con la misión de promover la paz mundial y la amistad. El Cuerpo de Paz tiene tres objetivos: (1) Ayudar a los pueblos de los países interesados a satisfacer sus necesidades de hombres y mujeres capacitados, (2) Ayudar a promover una mejor comprensión de los estadounidenses por parte de los pueblos atendidos, y (3) Ayudar a promover una mejor comprensión de otros pueblos por parte de los estadounidenses. Desde 1961, más de 240,000 estadounidenses han servido en 140 países. Actualmente, el Cuerpo de Paz tiene más de 3,200 voluntarios trabajando en 56 países anfitriones en seis sectores: agricultura, desarrollo económico comunitario, educación, medio ambiente, salud y juventud en desarrollo.`,
    fr: `Le Corps de la Paix est un programme de bénévolat géré par le gouvernement des États-Unis. Il a été créé par le président John F. Kennedy le 1er mars 1961 avec pour mission de promouvoir la paix mondiale et l'amitié. Le Corps de la Paix a trois objectifs : (1) Aider les peuples des pays intéressés à satisfaire leurs besoins en hommes et femmes qualifiés, (2) Aider à promouvoir une meilleure compréhension des Américains de la part des peuples servis, et (3) Aider à promouvoir une meilleure compréhension des autres peuples de la part des Américains. Depuis 1961, plus de 240 000 Américains ont servi dans 140 pays. Actuellement, le Corps de la Paix compte plus de 3 200 volontaires travaillant dans 56 pays d'accueil dans six secteurs : agriculture, développement économique communautaire, éducation, environnement, santé et jeunesse en développement.`,
    pt: `O Corpo de Paz é um programa de voluntariado administrado pelo governo dos Estados Unidos. Foi estabelecido pelo presidente John F. Kennedy em 1º de março de 1961 com a missão de promover a paz mundial e a amizade. O Corpo de Paz tem três objetivos: (1) Ajudar os povos dos países interessados a atender suas necessidades de homens e mulheres treinados, (2) Ajudar a promover uma melhor compreensão dos americanos por parte dos povos atendidos, e (3) Ajudar a promover uma melhor compreensão de outros povos por parte dos americanos. Desde 1961, mais de 240.000 americanos serviram em 140 países. Atualmente, o Corpo de Paz tem mais de 3.200 voluntários trabalhando em 56 países anfitriões em seis setores: agricultura, desenvolvimento econômico comunitário, educação, meio ambiente, saúde e juventude em desenvolvimento.`,
    zh: `和平队是由美国政府运营的志愿者项目。它由约翰·F·肯尼迪总统于1961年3月1日创立，使命是促进世界和平与友谊。和平队有三个目标：（1）帮助感兴趣国家的人民满足他们对受过训练的男女的需求，（2）帮助促进被服务人民对美国人的更好理解，（3）帮助促进美国人对其他民族的更好理解。自1961年以来，超过240,000名美国公民在140个国家服务。目前，和平队有超过3,200名志愿者在56个东道国的六个领域工作：农业、社区经济发展、教育、环境、健康和青年发展。`,
    ar: `فيلق السلام هو برنامج تطوعي يديره حكومة الولايات المتحدة. أسسه الرئيس جون إف كينيدي في الأول من مارس 1961 بمهمة تعزيز السلام العالمي والصداقة. لفيلق السلام ثلاثة أهداف: (1) مساعدة شعوب البلدان المهتمة في تلبية احتياجاتها من الرجال والنساء المدربين، (2) المساعدة في تعزيز فهم أفضل للأمريكيين من جانب الشعوب المخدومة، و(3) المساعدة في تعزيز فهم أفضل للشعوب الأخرى من جانب الأمريكيين. منذ عام 1961، خدم أكثر من 240,000 مواطن أمريكي في 140 دولة. حالياً، لدى فيلق السلام أكثر من 3,200 متطوع يعملون في 56 دولة مضيفة في ستة قطاعات: الزراعة والتنمية الاقتصادية المجتمعية والتعليم والبيئة والصحة والشباب في التنمية.`,
  },
  'doc-002': {
    en: '',
    es: `Para postularse al Cuerpo de Paz, debe ser ciudadano estadounidense y tener al menos 18 años. No hay límite máximo de edad. El proceso de solicitud incluye: (1) Crear una cuenta en peacecorps.gov, (2) Completar la solicitud en línea incluyendo su currículum, declaración de motivación y referencias, (3) Entrevista con un reclutador, (4) Obtener autorización médica y legal, (5) Aceptar su invitación para servir. Todo el proceso generalmente toma de 6 a 12 meses. La mayoría de los voluntarios sirven por 27 meses (3 meses de capacitación más 24 meses de servicio). Puede postularse a programas específicos o estar abierto a cualquier asignación. Visite peacecorps.gov/apply para comenzar su solicitud hoy.`,
    fr: `Pour postuler au Corps de la Paix, vous devez être citoyen américain et avoir au moins 18 ans. Il n'y a pas de limite d'âge supérieure. Le processus de candidature comprend : (1) Créer un compte sur peacecorps.gov, (2) Remplir la candidature en ligne comprenant votre CV, lettre de motivation et références, (3) Entretien avec un recruteur, (4) Obtenir les autorisations médicales et légales, (5) Accepter votre invitation à servir. L'ensemble du processus prend généralement de 6 à 12 mois. La plupart des volontaires servent pendant 27 mois (3 mois de formation plus 24 mois de service). Vous pouvez postuler à des programmes spécifiques ou être ouvert à toute affectation. Visitez peacecorps.gov/apply pour commencer votre candidature.`,
    pt: `Para se candidatar ao Corpo de Paz, você deve ser cidadão americano e ter pelo menos 18 anos. Não há limite máximo de idade. O processo de candidatura inclui: (1) Criar uma conta em peacecorps.gov, (2) Completar a candidatura online incluindo seu currículo, declaração de motivação e referências, (3) Entrevista com um recrutador, (4) Obter autorização médica e legal, (5) Aceitar seu convite para servir. Todo o processo geralmente leva de 6 a 12 meses. A maioria dos voluntários serve por 27 meses (3 meses de treinamento mais 24 meses de serviço). Você pode se candidatar a programas específicos ou estar aberto a qualquer designação. Visite peacecorps.gov/apply para começar sua candidatura hoje.`,
    zh: `申请和平队，您必须是美国公民且年满18岁。没有年龄上限。申请流程包括：（1）在peacecorps.gov创建账户，（2）完成在线申请，包括简历、动机声明和推荐信，（3）与招聘人员面试，（4）获得医疗和法律许可，（5）接受服务邀请。整个过程通常需要6至12个月。大多数志愿者服务27个月（3个月培训加24个月服务）。您可以申请特定项目或对任何任务保持开放。访问peacecorps.gov/apply开始您的申请。`,
    ar: `للتقدم لفيلق السلام، يجب أن تكون مواطناً أمريكياً وعمرك 18 عاماً على الأقل. لا يوجد حد أقصى للعمر. تشمل عملية التقديم: (1) إنشاء حساب على peacecorps.gov، (2) إكمال الطلب عبر الإنترنت بما في ذلك سيرتك الذاتية وبيان الدافع والمراجع، (3) مقابلة مع مجند، (4) الحصول على الموافقة الطبية والقانونية، (5) قبول دعوتك للخدمة. تستغرق العملية بأكملها عادةً من 6 إلى 12 شهراً. يخدم معظم المتطوعين لمدة 27 شهراً (3 أشهر تدريب بالإضافة إلى 24 شهراً من الخدمة). يمكنك التقدم لبرامج محددة أو البقاء منفتحاً على أي مهمة. قم بزيارة peacecorps.gov/apply لبدء طلبك اليوم.`,
  },
  'doc-004': {
    en: '',
    es: `Los voluntarios del Cuerpo de Paz reciben numerosos beneficios incluyendo: subsidio de vida para cubrir vivienda, alimentación y transporte local; cobertura médica y dental completa durante el servicio; 48 días de vacaciones en 2 años; capacitación en idiomas y técnica; aplazamiento o cancelación parcial de préstamos estudiantiles (préstamos Perkins); oportunidades de posgrado incluyendo becas en más de 200 universidades; elegibilidad no competitiva (NCE) para empleo federal durante 12 meses después del servicio; subsidio de readaptación de aproximadamente $10,000 después de completar el servicio; apoyo profesional y red de contactos a través de la comunidad de voluntarios retornados. El servicio del Cuerpo de Paz también se considera empleo calificado bajo el programa de Condonación de Préstamos por Servicio Público (PSLF).`,
    fr: `Les volontaires du Corps de la Paix reçoivent de nombreux avantages, notamment : une allocation de subsistance pour couvrir le logement, la nourriture et le transport local ; une couverture médicale et dentaire complète pendant le service ; 48 jours de congé sur 2 ans ; une formation linguistique et technique ; un report ou une annulation partielle des prêts étudiants (prêts Perkins) ; des opportunités d'études supérieures, y compris des bourses dans plus de 200 universités ; une éligibilité non compétitive (NCE) pour un emploi fédéral pendant 12 mois après le service ; une allocation de réajustement d'environ 10 000 $ après avoir terminé le service ; un soutien professionnel et un réseau à travers la communauté des anciens volontaires. Le service au Corps de la Paix est également considéré comme un emploi qualifiant dans le cadre du programme de remise de prêts de la fonction publique (PSLF).`,
    pt: `Os voluntários do Corpo de Paz recebem numerosos benefícios, incluindo: subsídio de vida para cobrir moradia, alimentação e transporte local; cobertura médica e odontológica completa durante o serviço; 48 dias de férias em 2 anos; treinamento linguístico e técnico; adiamento ou cancelamento parcial de empréstimos estudantis (empréstimos Perkins); oportunidades de pós-graduação incluindo bolsas em mais de 200 universidades; elegibilidade não competitiva (NCE) para emprego federal por 12 meses após o serviço; subsídio de readaptação de aproximadamente US$10.000 após completar o serviço; apoio profissional e rede de contatos através da comunidade de voluntários retornados. O serviço no Corpo de Paz também é considerado emprego qualificado no programa de Perdão de Empréstimos por Serviço Público (PSLF).`,
    zh: `和平队志愿者获得众多福利，包括：生活补贴用于支付住房、食品和当地交通；服务期间的全面医疗和牙科保险；2年内48天假期；语言和技术培训；学生贷款延期或部分免除（Perkins贷款）；研究生院机会，包括200多所大学的奖学金和助学金；服务后12个月的联邦就业非竞争性资格（NCE）；完成服务后约10,000美元的再适应津贴；通过回国志愿者社区获得的职业支持和人脉网络。和平队服务也被视为公共服务贷款豁免（PSLF）计划下的合格就业。`,
    ar: `يحصل متطوعو فيلق السلام على فوائد عديدة تشمل: بدل معيشة لتغطية السكن والطعام والنقل المحلي؛ تغطية طبية وأسنان كاملة أثناء الخدمة؛ 48 يوم إجازة خلال سنتين؛ تدريب لغوي وتقني؛ تأجيل أو إلغاء جزئي لقروض الطلاب (قروض بيركنز)؛ فرص الدراسات العليا بما في ذلك المنح الدراسية في أكثر من 200 جامعة؛ الأهلية غير التنافسية (NCE) للتوظيف الفيدرالي لمدة 12 شهراً بعد الخدمة؛ بدل إعادة التكيف بحوالي 10,000 دولار بعد إكمال الخدمة؛ دعم مهني وشبكة علاقات من خلال مجتمع المتطوعين العائدين. تعتبر خدمة فيلق السلام أيضاً توظيفاً مؤهلاً بموجب برنامج إعفاء قروض الخدمة العامة (PSLF).`,
  },
  'doc-006': {
    en: '',
    es: `Para ser elegible para el servicio del Cuerpo de Paz, debe: ser ciudadano estadounidense; tener al menos 18 años (sin límite máximo de edad); completar una solicitud exhaustiva; pasar las autorizaciones médicas y legales; comprometerse a 27 meses de servicio para el programa PCV. Aunque no siempre se requiere un título universitario, la mayoría de los puestos prefieren candidatos con licenciatura y experiencia relevante. Las parejas pueden servir juntas si ambos son seleccionados y asignados al mismo país. El Cuerpo de Paz no puede aceptar solicitantes que tengan préstamos federales en mora, estén en libertad condicional o probatoria, o que tengan ciertas condenas penales. El conocimiento de un idioma extranjero es útil pero no siempre requerido, ya que los voluntarios reciben 3 meses de capacitación intensiva en idiomas.`,
    fr: `Pour être éligible au service du Corps de la Paix, vous devez : être citoyen américain ; avoir au moins 18 ans (pas de limite d'âge supérieure) ; remplir une candidature complète ; passer les autorisations médicales et légales ; s'engager pour 27 mois de service pour le programme PCV. Bien qu'un diplôme universitaire ne soit pas toujours requis, la plupart des postes préfèrent les candidats titulaires d'une licence et ayant une expérience pertinente. Les couples peuvent servir ensemble si les deux sont sélectionnés et affectés au même pays. Le Corps de la Paix ne peut pas accepter les candidats ayant des prêts fédéraux en défaut, en liberté conditionnelle, ou ayant certaines condamnations pénales. La connaissance d'une langue étrangère est utile mais pas toujours requise car les volontaires reçoivent 3 mois de formation linguistique intensive.`,
    pt: `Para ser elegível para o serviço do Corpo de Paz, você deve: ser cidadão americano; ter pelo menos 18 anos (sem limite máximo de idade); completar uma candidatura completa; passar nas autorizações médicas e legais; comprometer-se com 27 meses de serviço para o programa PCV. Embora um diploma universitário nem sempre seja exigido, a maioria das posições prefere candidatos com bacharelado e experiência relevante. Casais podem servir juntos se ambos forem selecionados e designados para o mesmo país. O Corpo de Paz não pode aceitar candidatos com empréstimos federais em atraso, em liberdade condicional, ou com certas condenações criminais. O conhecimento de um idioma estrangeiro é útil, mas nem sempre necessário, pois os voluntários recebem 3 meses de treinamento intensivo de idiomas.`,
    zh: `要获得和平队服务资格，您必须：是美国公民；年满18岁（无年龄上限）；完成详尽的申请；通过医疗和法律审查；承诺PCV项目27个月的服务。虽然不总是要求大学学位，但大多数职位优先考虑拥有学士学位和相关经验的候选人。夫妻可以一起服务，前提是双方都被选中并分配到同一个国家。和平队不能接受有联邦贷款违约、缓刑或假释、或有某些刑事定罪的申请人。外语知识有帮助但并非总是必需的，因为志愿者会接受3个月的强化语言培训。`,
    ar: `لتكون مؤهلاً لخدمة فيلق السلام، يجب عليك: أن تكون مواطناً أمريكياً؛ أن يكون عمرك 18 عاماً على الأقل (لا يوجد حد أقصى للعمر)؛ إكمال طلب شامل؛ اجتياز التصاريح الطبية والقانونية؛ الالتزام بـ 27 شهراً من الخدمة لبرنامج PCV. على الرغم من أن الشهادة الجامعية ليست مطلوبة دائماً، فإن معظم المناصب تفضل المرشحين الحاصلين على درجة البكالوريوس والخبرة ذات الصلة. يمكن للأزواج الخدمة معاً إذا تم اختيار كليهما وتعيينهما في نفس البلد. لا يمكن لفيلق السلام قبول المتقدمين الذين لديهم قروض فيدرالية متعثرة، أو تحت المراقبة، أو لديهم إدانات جنائية معينة. معرفة لغة أجنبية مفيدة ولكنها ليست مطلوبة دائماً حيث يتلقى المتطوعون 3 أشهر من التدريب اللغوي المكثف.`,
  },
  'doc-013': {
    en: '',
    es: `Las parejas casadas y las parejas de hecho pueden servir juntas en el Cuerpo de Paz. Ambas personas deben presentar su solicitud por separado y cumplir con todos los requisitos de elegibilidad. Las parejas son asignadas al mismo país y comunidad. El Cuerpo de Paz no acepta voluntarios con dependientes menores de 18 años. Las parejas del mismo sexo pueden servir juntas, aunque el Cuerpo de Paz tiene en cuenta las leyes y normas culturales de los países anfitriones al tomar decisiones de ubicación. Las parejas deben discutir su deseo de servir juntas con un reclutador tempranamente en el proceso.`,
    fr: `Les couples mariés et les partenaires domestiques peuvent servir ensemble dans le Corps de la Paix. Les deux individus doivent postuler séparément et satisfaire à toutes les conditions d'éligibilité. Les couples sont affectés au même pays et à la même communauté. Le Corps de la Paix n'accepte pas les volontaires ayant des personnes à charge de moins de 18 ans. Les couples de même sexe peuvent servir ensemble, bien que le Corps de la Paix prenne en compte les lois et les normes culturelles des pays d'accueil lors des décisions de placement. Les couples doivent discuter de leur souhait de servir ensemble avec un recruteur dès le début du processus.`,
    pt: `Casais e parceiros domésticos podem servir juntos no Corpo de Paz. Ambos os indivíduos devem se candidatar separadamente e atender a todos os requisitos de elegibilidade. Os casais são designados para o mesmo país e comunidade. O Corpo de Paz não aceita voluntários com dependentes menores de 18 anos. Casais do mesmo sexo podem servir juntos, embora o Corpo de Paz leve em consideração as leis e normas culturais dos países anfitriões ao tomar decisões de alocação. Os casais devem discutir seu desejo de servir juntos com um recrutador no início do processo.`,
    zh: `已婚夫妇和同居伴侣可以一起在和平队服务。双方必须分别申请并满足所有资格要求。夫妇被分配到同一个国家和社区。和平队不接受有18岁以下受抚养人的志愿者。同性伴侣可以一起服务，但和平队在做出安置决定时会考虑东道国的法律和文化规范。夫妇应在申请过程的早期与招聘人员讨论他们一起服务的愿望。`,
    ar: `يمكن للأزواج المتزوجين والشركاء المنزليين الخدمة معاً في فيلق السلام. يجب على كلا الفردين التقدم بشكل منفصل واستيفاء جميع متطلبات الأهلية. يتم تعيين الأزواج في نفس البلد والمجتمع. لا يقبل فيلق السلام المتطوعين الذين لديهم معالون تحت سن 18 عاماً. يمكن للأزواج من نفس الجنس الخدمة معاً، على الرغم من أن فيلق السلام يأخذ في الاعتبار قوانين وأعراف البلدان المضيفة عند اتخاذ قرارات التنسيب. يجب على الأزواج مناقشة رغبتهم في الخدمة معاً مع مجند في وقت مبكر من العملية.`,
  },
};

/**
 * Translate a knowledge base document's content to the target language.
 * Returns translated content if available, otherwise returns English original.
 */
export function translateContent(docId: string, englishContent: string, language: SupportedLanguage): string {
  if (language === 'en') return englishContent;

  const translations = TRANSLATED_CONTENT[docId];
  if (translations && translations[language]) {
    return translations[language];
  }

  // Fallback: return English with a translation note
  return englishContent;
}
